"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Bath, BedDouble, Bell, Bot, CheckCircle2, ChevronDown, Heart, House, MapPin, Mic, Search, ShieldCheck, Sparkles, SquareStack, Store, UploadCloud, UsersRound } from "lucide-react";

const images = {
  hero: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=85",
  home1: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=85",
  home2: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=85",
  home3: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=85",
  home4: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=85",
  home5: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=85",
  map: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=900&q=80",
};

const categories = [["1 BHK", "Apartments", images.home1], ["2 BHK", "Apartments", images.home2], ["3 BHK", "Apartments", images.home4], ["4 BHK+", "Apartments", images.home5], ["Independent", "Houses", images.home3], ["Villas", "Houses", images.home3], ["PG & Coliving", "Shared spaces", images.home2], ["Hotels", "Near You", images.home1]];
const properties = [["₹28,000", "2 BHK Apartment", "Gachibowli, Hyderabad", "Near Metro", images.home1], ["₹45,000", "3 BHK Apartment", "HITEC City, Hyderabad", "Premium", images.home2], ["₹18,000", "1 BHK Apartment", "Kondapur, Hyderabad", "Budget Friendly", images.home4], ["₹65,000", "4 BHK Apartment", "Jubilee Hills, Hyderabad", "Luxury", images.home5]];

function PropertyCard({ property }: { property: string[] }) {
  return <article className="group overflow-hidden rounded-xl border border-slate-100 bg-white shadow-[0_8px_24px_rgba(43,67,117,.08)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_15px_30px_rgba(43,67,117,.14)]"><div className="relative h-32 overflow-hidden"><img src={property[4]} alt="Modern apartment" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><button aria-label="Save property" className="absolute right-2 top-2 rounded-full bg-white/90 p-1.5 text-slate-500"><Heart className="size-4" /></button></div><div className="p-3"><p className="text-sm font-extrabold text-slate-900">{property[0]} <span className="text-[10px] font-medium">/ month</span></p><p className="mt-1 text-xs font-semibold text-slate-700">{property[1]}</p><p className="mt-1 text-[10px] text-slate-500">{property[2]}</p><div className="mt-2 flex items-center justify-between text-[10px] text-slate-500"><span className="inline-flex gap-1"><BedDouble className="size-3" /> 2</span><span className="inline-flex gap-1"><Bath className="size-3" /> 2</span><span>1,200 sqft</span></div><span className="mt-2 inline-block rounded-full bg-indigo-50 px-2 py-1 text-[9px] font-bold text-indigo-600">{property[3]}</span></div></article>;
}

export default function LandingPage() {
  const router = useRouter();
  const [query, setQuery] = useState("2BHK near metro in Hyderabad");
  const [mode, setMode] = useState("Rent");
  const submit = (event: FormEvent) => { event.preventDefault(); router.push(`/search?q=${encodeURIComponent(query)}`); };
  const features = [[UploadCloud,"Real-time Data","Fresh listings via automated workers"],[MapPin,"Location Intelligence","Nearby metro, schools, hospitals, offices"],[Bot,"AI Assistant","Ask in natural language"],[ShieldCheck,"Verified Listings","From trusted sources"],[SquareStack,"Smart Comparison","Compare properties easily"],[Bell,"Save & Track","Save properties and get alerts"]];
  return <div className="bg-[#f6f9ff] text-[#0b1740]">
    <section className="relative overflow-hidden bg-[#251bd4] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(217,99,230,.9),transparent_23%),radial-gradient(circle_at_70%_52%,rgba(255,144,122,.9),transparent_25%),linear-gradient(120deg,#2b31d7_0%,#6e42dc_50%,#ff8b84_100%)]" /><div className="absolute inset-x-0 bottom-0 h-60 bg-cover bg-center opacity-45 mix-blend-luminosity" style={{backgroundImage:`url(${images.hero})`}} /><div className="relative mx-auto max-w-[1500px] px-5 pb-7 pt-4 lg:px-8">
      <header className="flex items-center justify-between text-xs"><Link href="/" className="flex items-center gap-2 text-sm font-extrabold"><span className="grid size-6 place-items-center rounded-md bg-white text-indigo-600"><House className="size-4 fill-current" /></span>RealEstateGPT</Link><nav className="hidden gap-7 text-white/95 md:flex"><Link href="/search">Buy</Link><button onClick={() => setMode("Rent")}>Rent</button><a href="#categories">PG & Coliving</a><a href="#properties">Hotels</a><a href="#explore">Explore <ChevronDown className="ml-1 inline size-3" /></a><Link href="/assistant">AI Assistant</Link></nav><div className="flex items-center gap-5"><Link href="/auth/login">Sign in</Link><Link href="/auth/register" className="rounded-lg bg-[#3d42ff] px-4 py-2.5 font-bold shadow-lg shadow-indigo-900/30">Get Started</Link></div></header>
      <div className="grid min-h-[370px] items-center gap-9 pt-10 lg:grid-cols-[1fr_340px] lg:px-3"><div className="max-w-[620px]"><span className="inline-flex items-center gap-1 rounded-full bg-white/20 px-3 py-1.5 text-[10px] font-bold"><Sparkles className="size-3" /> AI-Powered Real Estate</span><h1 className="mt-4 text-4xl font-black leading-[1.08] tracking-tight sm:text-5xl">Find your perfect<br />home with AI</h1><p className="mt-3 max-w-[530px] text-sm leading-6 text-white/95">Search real properties, get location insights, compare options, and make smarter decisions. Real-time data. Real answers.</p></div>
      <form onSubmit={submit} className="rounded-2xl bg-white p-3 text-slate-800 shadow-2xl shadow-indigo-900/20"><div className="grid grid-cols-4 rounded-xl bg-[#f4f7ff] p-1 text-[10px] font-bold"><button type="button" onClick={() => setMode("Buy")} className={`rounded-lg py-2 ${mode === "Buy" ? "bg-white shadow text-indigo-600" : ""}`}>Buy</button><button type="button" onClick={() => setMode("Rent")} className={`rounded-lg py-2 ${mode === "Rent" ? "bg-white shadow text-indigo-600" : ""}`}>Rent</button><button type="button" className="py-2">Hotels</button><button type="button" className="py-2">PG</button></div><div className="mt-3 flex items-center rounded-lg border border-slate-200 px-3 py-3"><Search className="size-4 text-indigo-500" /><input value={query} onChange={e => setQuery(e.target.value)} className="min-w-0 flex-1 px-2 text-[11px] outline-none" /><Mic className="size-4 text-indigo-700" /></div><button type="button" className="mt-2 flex items-center gap-1 text-[9px] font-semibold text-indigo-600"><MapPin className="size-3" /> Use my current location</button><div className="mt-3 grid grid-cols-3 gap-2 text-[9px]"><label>City / Locality<input value="Hyderabad" readOnly className="mt-1 w-full rounded-md border border-slate-200 p-2 text-[10px]" /></label><label>Property Type<select className="mt-1 w-full rounded-md border border-slate-200 p-2 text-[10px]"><option>Apartment</option></select></label><label>Budget (₹)<select className="mt-1 w-full rounded-md border border-slate-200 p-2 text-[10px]"><option>Any</option></select></label></div><button className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-[#287bff] to-[#a317e9] py-3 text-[11px] font-bold text-white"><Search className="size-3" /> Search Properties</button></form></div>
      <div className="flex flex-wrap gap-x-10 gap-y-3 border-t border-white/20 pt-4 text-center text-xs font-bold"><span><b className="block text-xl">50K+</b><small className="font-medium">Properties</small></span><span><b className="block text-xl">8+</b><small className="font-medium">Cities</small></span><span><b className="block text-xl">Real-time</b><small className="font-medium">Updated</small></span><span><b className="block text-xl">AI</b><small className="font-medium">Powered</small></span></div></div></section>
    <main className="mx-auto max-w-[1500px] space-y-4 px-5 py-4 lg:px-8"><section id="categories" className="rounded-xl bg-white p-3 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold">Explore by Category</h2><p className="text-[10px] text-slate-500">Find exactly what you need, organized for real life.</p></div><a href="#properties" className="text-xs font-bold text-indigo-600">View all <ArrowRight className="inline size-3" /></a></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-8">{categories.map(([title, subtitle, image]) => <button key={title} onClick={() => router.push(`/search?type=${title}`)} className="overflow-hidden rounded-lg border border-slate-100 bg-white text-left shadow-sm"><img src={image} alt="Property category" className="h-16 w-full object-cover" /><span className="block px-2 pt-1 text-[10px] font-bold">{title}</span><span className="block px-2 pb-2 text-[9px] text-slate-500">{subtitle}</span></button>)}</div></section>
    <section className="rounded-xl bg-white p-3 shadow-sm"><h2 className="font-bold">Why RealEstateGPT?</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,copy]) => { const C=Icon as typeof Bot; return <div key={String(title)} className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-indigo-50 text-indigo-600"><C className="size-4" /></span><div><h3 className="text-[11px] font-bold">{String(title)}</h3><p className="mt-1 text-[9px] text-slate-500">{String(copy)}</p></div></div>})}</div></section>
    <section id="explore" className="grid gap-4 lg:grid-cols-[1fr_1fr]"><div className="relative min-h-36 overflow-hidden rounded-xl bg-indigo-700 p-5 text-white"><img src={images.map} alt="Neighbourhood map" className="absolute inset-0 h-full w-full object-cover opacity-30 mix-blend-overlay" /><div className="relative"><h2 className="text-lg font-bold">Discover properties<br />near you</h2><p className="mt-2 text-[10px] text-white/85">Allow location access to show properties and PGs around you.</p><button className="mt-4 rounded-md bg-white px-3 py-2 text-[10px] font-bold text-indigo-600">Detect My Location</button></div></div><div className="rounded-xl bg-white p-5 shadow-sm"><p className="text-[10px] font-bold">Or enter your location manually</p><div className="mt-3 flex gap-2"><div className="flex flex-1 items-center rounded-lg border border-slate-200 px-3"><Search className="size-3 text-slate-400" /><input className="w-full p-2 text-[10px] outline-none" placeholder="Enter city, locality, or landmark" /></div><Link href="/search" className="rounded-lg bg-indigo-600 px-5 py-2 text-[10px] font-bold text-white">Search</Link></div><p className="mt-4 text-[9px] font-semibold text-slate-500">Popular Searches</p><div className="mt-2 flex flex-wrap gap-2">{["HITEC City","Gachibowli","Kondapur","Madhapur","Banjara Hills"].map(x=><button key={x} className="rounded-full bg-indigo-50 px-3 py-1 text-[9px] text-indigo-700">{x}</button>)}</div></div></section>
    <section id="properties" className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-xl bg-white p-3 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Featured Properties</h2><div className="mt-2 flex gap-4 text-[10px] font-semibold text-slate-500"><button className="text-indigo-600">For Rent</button><button>For Sale</button><button>Hotels</button><button>PG & Coliving</button></div></div><Link href="/search" className="text-[10px] font-bold text-indigo-600">View all <ArrowRight className="inline size-3" /></Link></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{properties.map((p) => <PropertyCard key={p[0]+p[2]} property={p} />)}</div></div><div className="rounded-xl bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-lg bg-indigo-50"><Bot className="size-4 text-indigo-600" /></span><b className="text-xs">AI Assistant</b></div><div className="mt-5 text-center"><Bot className="mx-auto size-7 text-indigo-600" /><h2 className="mt-2 font-bold">Ask RealEstateGPT</h2><p className="mt-1 text-[10px] text-slate-500">Find, compare, get info, and more.</p><button onClick={() => router.push("/assistant")} className="mt-3 rounded-full bg-indigo-100 px-4 py-2 text-[10px] text-indigo-700">Find me a 2BHK for rent under ₹30,000 near metro</button></div><ul className="mt-5 space-y-2 text-[10px] text-slate-500"><li><CheckCircle2 className="mr-2 inline size-3 text-green-500" />Searching properties...</li><li><CheckCircle2 className="mr-2 inline size-3 text-green-500" />Checking metro proximity...</li><li><CheckCircle2 className="mr-2 inline size-3 text-green-500" />Found 12 matches!</li></ul><div className="mt-4 flex items-center rounded-lg border border-slate-200 px-3"><input className="w-full p-2 text-[10px] outline-none" placeholder="Ask anything about real estate..." /><button onClick={() => router.push("/assistant")} aria-label="Open AI Assistant" className="rounded-md bg-indigo-600 p-1.5 text-white"><ArrowRight className="size-3" /></button></div></div></section>
    <section className="grid gap-4 pb-3 lg:grid-cols-[1fr_1fr]"><div className="rounded-xl bg-white p-5 shadow-sm"><h2 className="font-bold">Your property search, simplified</h2><p className="mt-2 text-xs text-slate-500">Find a place you&apos;ll love with smart filters, live location insights and an assistant that understands your needs.</p><Link href="/search" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-indigo-600">Start exploring <ArrowRight className="size-3" /></Link></div><div className="rounded-xl bg-white p-5 shadow-sm"><h2 className="font-bold">Data that keeps moving</h2><div className="mt-4 flex items-center justify-between text-center text-[10px] font-semibold text-slate-600"><span className="grid gap-2"><Store className="mx-auto size-5 text-indigo-600" />Property Sources</span><ArrowRight className="size-4 text-indigo-400" /><span className="grid gap-2"><UsersRound className="mx-auto size-5 text-indigo-600" />Data Workers</span><ArrowRight className="size-4 text-indigo-400" /><span className="grid gap-2"><ShieldCheck className="mx-auto size-5 text-teal-500" />Verified Listings</span></div></div></section></main>
  </div>;
}
