import type { MetadataRoute } from "next";

/**
 * Private/authenticated surfaces are excluded from indexing; the public
 * discovery surfaces stay crawlable. Regenerated by the deployment itself so
 * the host is never hardcoded to a placeholder domain.
 */
export default function robots(): MetadataRoute.Robots {
  const base = (
    process.env.NEXT_PUBLIC_SITE_URL?.trim() || "https://realestate-gpt-inky.vercel.app"
  ).replace(/\/+$/, "");

  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/admin", "/saved", "/compare", "/assistant", "/auth/", "/discoveries/"],
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}
