"""RealEstateGPT - Seed data: realistic properties across Indian cities"""

import re
from datetime import datetime, timedelta, timezone

AMENITIES = [
    {"name": "Swimming Pool", "category": "lifestyle", "icon": "waves"},
    {"name": "Gym", "category": "lifestyle", "icon": "dumbbell"},
    {"name": "Clubhouse", "category": "lifestyle", "icon": "building"},
    {"name": "Children's Play Area", "category": "lifestyle", "icon": "baby"},
    {"name": "Jogging Track", "category": "lifestyle", "icon": "footprints"},
    {"name": "Garden", "category": "lifestyle", "icon": "tree-palm"},
    {"name": "Indoor Games", "category": "lifestyle", "icon": "gamepad-2"},
    {"name": "Party Hall", "category": "lifestyle", "icon": "party-popper"},
    {"name": "24/7 Security", "category": "safety", "icon": "shield"},
    {"name": "CCTV Surveillance", "category": "safety", "icon": "camera"},
    {"name": "Intercom", "category": "safety", "icon": "phone"},
    {"name": "Fire Safety", "category": "safety", "icon": "flame"},
    {"name": "Power Backup", "category": "convenience", "icon": "zap"},
    {"name": "Water Supply", "category": "convenience", "icon": "droplets"},
    {"name": "Lift", "category": "convenience", "icon": "arrow-up-down"},
    {"name": "Car Parking", "category": "convenience", "icon": "car"},
    {"name": "Visitor Parking", "category": "convenience", "icon": "parking-circle"},
    {"name": "Rain Water Harvesting", "category": "sustainability", "icon": "cloud-rain"},
    {"name": "Solar Panel", "category": "sustainability", "icon": "sun"},
    {"name": "Waste Management", "category": "sustainability", "icon": "recycle"},
    {"name": "Tennis Court", "category": "sports", "icon": "trophy"},
    {"name": "Basketball Court", "category": "sports", "icon": "circle-dot"},
    {"name": "Badminton Court", "category": "sports", "icon": "trophy"},
    {"name": "Yoga Room", "category": "wellness", "icon": "heart"},
    {"name": "Spa", "category": "wellness", "icon": "sparkles"},
    {"name": "Library", "category": "lifestyle", "icon": "book-open"},
    {"name": "Co-working Space", "category": "convenience", "icon": "laptop"},
    {"name": "EV Charging", "category": "convenience", "icon": "plug-zap"},
    {"name": "Piped Gas", "category": "convenience", "icon": "flame"},
    {"name": "Vastu Compliant", "category": "design", "icon": "compass"},
]


def _slug(title: str) -> str:
    s = title.lower().strip()
    s = re.sub(r'[^a-z0-9\s-]', '', s)
    s = re.sub(r'[\s]+', '-', s)
    return s


PROPERTIES = [
    # ─── HYDERABAD ────────────────────────────────────────
    {
        "title": "Prestige Luxe Heights 2BHK in HITEC City",
        "description": "Modern 2BHK apartment in the heart of HITEC City, Hyderabad. Walking distance to major IT parks including Mindspace and Inorbit Mall. The apartment features premium fittings, Italian marble flooring, and a modular kitchen with chimney. The gated community offers world-class amenities including an infinity pool, sky lounge, and 24/7 concierge service. RERA approved with clear title.",
        "price": 6500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1150, "carpet_area_sqft": 980,
        "floor": 12, "total_floors": 25, "property_age": 2, "facing": "East",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "HITEC City", "city": "Hyderabad", "state": "Telangana", "pincode": "500081",
        "latitude": 17.4435, "longitude": 78.3772, "builder_name": "Prestige Group",
        "project_name": "Prestige Luxe Heights", "is_featured": True,
        "price_per_sqft": 5652, "maintenance_charge": 3500,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Jogging Track", "EV Charging"],
    },
    {
        "title": "Aparna Serene Park 3BHK Gachibowli",
        "description": "Spacious 3BHK apartment in Gachibowli, close to Financial District and ISB. Features large balconies with city views, designer bathrooms, and premium woodwork. The complex includes a temperature-controlled pool, multi-cuisine restaurant, and business center. Located near top schools including DPS and Oakridge.",
        "price": 9500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 3, "balconies": 2, "area_sqft": 1650, "carpet_area_sqft": 1400,
        "floor": 8, "total_floors": 18, "property_age": 1, "facing": "North-East",
        "furnishing": "semi-furnished", "parking": 2, "construction_status": "ready",
        "locality": "Gachibowli", "city": "Hyderabad", "state": "Telangana", "pincode": "500032",
        "latitude": 17.4400, "longitude": 78.3489, "builder_name": "Aparna Constructions",
        "project_name": "Aparna Serene Park", "is_featured": True,
        "price_per_sqft": 5757, "maintenance_charge": 5000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Tennis Court", "Badminton Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Visitor Parking", "Children's Play Area", "Jogging Track", "Party Hall", "Co-working Space", "Piped Gas"],
    },
    {
        "title": "My Home Bhooja 4BHK Madhapur Premium",
        "description": "Ultra-luxury 4BHK residence at My Home Bhooja, Madhapur. Premium living with Italian marble throughout, German kitchen fittings, VRV air conditioning, and home automation. The 15-acre township features a 30,000 sq ft clubhouse, Olympic-size pool, and landscaped gardens. Walking distance to Durgam Cheruvu Metro Station.",
        "price": 22000000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 4, "bathrooms": 4, "balconies": 3, "area_sqft": 3200, "carpet_area_sqft": 2700,
        "floor": 15, "total_floors": 30, "property_age": 3, "facing": "South-East",
        "furnishing": "furnished", "parking": 2, "construction_status": "ready",
        "locality": "Madhapur", "city": "Hyderabad", "state": "Telangana", "pincode": "500081",
        "latitude": 17.4486, "longitude": 78.3908, "builder_name": "My Home Group",
        "project_name": "My Home Bhooja", "is_featured": True,
        "price_per_sqft": 6875, "maintenance_charge": 12000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Tennis Court", "Spa", "Library", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Visitor Parking", "Children's Play Area", "Jogging Track", "Party Hall", "Indoor Games", "Yoga Room", "Solar Panel", "EV Charging", "Vastu Compliant"],
    },
    {
        "title": "Ramky One Galaxia 2BHK Kondapur",
        "description": "Well-designed 2BHK in Kondapur near Botanical Garden. Ideal for IT professionals with quick access to HITEC City and Gachibowli. Features cross-ventilation design, modular kitchen, and covered car parking. Close to metro station, hospitals, and supermarkets.",
        "price": 5200000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1050, "carpet_area_sqft": 890,
        "floor": 5, "total_floors": 14, "property_age": 4, "facing": "West",
        "furnishing": "unfurnished", "parking": 1, "construction_status": "ready",
        "locality": "Kondapur", "city": "Hyderabad", "state": "Telangana", "pincode": "500084",
        "latitude": 17.4601, "longitude": 78.3530, "builder_name": "Ramky Group",
        "project_name": "Ramky One Galaxia",
        "price_per_sqft": 4952, "maintenance_charge": 2800,
        "amenity_names": ["Swimming Pool", "Gym", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Rain Water Harvesting"],
    },
    {
        "title": "Muppas Indraprastha 3BHK Kukatpally",
        "description": "Affordable 3BHK apartment in Kukatpally, one of Hyderabad's well-connected suburbs. Near KPHB metro station, JNTU, and Forum Mall. Features spacious rooms, modern fixtures, and a large utility area. Family-friendly neighborhood with schools, parks, and healthcare facilities nearby.",
        "price": 6800000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 2, "balconies": 2, "area_sqft": 1400, "carpet_area_sqft": 1190,
        "floor": 3, "total_floors": 10, "property_age": 5, "facing": "North",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Kukatpally", "city": "Hyderabad", "state": "Telangana", "pincode": "500072",
        "latitude": 17.4849, "longitude": 78.3916, "builder_name": "Muppas Group",
        "project_name": "Muppas Indraprastha",
        "price_per_sqft": 4857, "maintenance_charge": 3000,
        "amenity_names": ["Gym", "24/7 Security", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Intercom", "Water Supply", "Piped Gas"],
    },
    {
        "title": "Rajapushpa Atria 2BHK Kokapet",
        "description": "New-age 2BHK apartment in Kokapet, the emerging luxury corridor of Hyderabad. Minutes from Financial District and ORR. Modern architecture with floor-to-ceiling windows, quartz countertops, and smart home features. The project is surrounded by greenery with lake views.",
        "price": 7200000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1200, "carpet_area_sqft": 1020,
        "floor": 18, "total_floors": 28, "property_age": 0, "facing": "South",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "under_construction",
        "locality": "Kokapet", "city": "Hyderabad", "state": "Telangana", "pincode": "500075",
        "latitude": 17.4050, "longitude": 78.3350, "builder_name": "Rajapushpa Properties",
        "project_name": "Rajapushpa Atria", "is_featured": True,
        "price_per_sqft": 6000, "maintenance_charge": 4000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Jogging Track", "EV Charging", "Solar Panel", "Rain Water Harvesting", "Co-working Space"],
    },
    {
        "title": "Phoenix Towers 1BHK Miyapur Compact",
        "description": "Compact and affordable 1BHK in Miyapur, perfect for young professionals or investors. Near Miyapur Metro Terminal, providing excellent connectivity. Features efficient space design, modular kitchen, and dedicated parking. Good rental demand area.",
        "price": 3200000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 1, "bathrooms": 1, "balconies": 1, "area_sqft": 650, "carpet_area_sqft": 550,
        "floor": 7, "total_floors": 12, "property_age": 3, "facing": "East",
        "furnishing": "unfurnished", "parking": 1, "construction_status": "ready",
        "locality": "Miyapur", "city": "Hyderabad", "state": "Telangana", "pincode": "500049",
        "latitude": 17.4965, "longitude": 78.3551, "builder_name": "Phoenix Developers",
        "project_name": "Phoenix Towers",
        "price_per_sqft": 4923, "maintenance_charge": 1500,
        "amenity_names": ["24/7 Security", "Power Backup", "Lift", "Car Parking", "Water Supply", "Intercom"],
    },
    {
        "title": "Lanco Hills 3BHK Manikonda Hillside",
        "description": "Elegant 3BHK in Lanco Hills, Manikonda. Nestled in a hillock with panoramic views of the city. Premium community with 72-acre township, golf course access, and international school within the complex. Close to Rajiv Gandhi International Airport via ORR.",
        "price": 11500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 3, "balconies": 2, "area_sqft": 1850, "carpet_area_sqft": 1570,
        "floor": 10, "total_floors": 22, "property_age": 6, "facing": "North-West",
        "furnishing": "semi-furnished", "parking": 2, "construction_status": "ready",
        "locality": "Manikonda", "city": "Hyderabad", "state": "Telangana", "pincode": "500089",
        "latitude": 17.4100, "longitude": 78.3850, "builder_name": "Lanco Group",
        "project_name": "Lanco Hills",
        "price_per_sqft": 6216, "maintenance_charge": 6500,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Tennis Court", "Basketball Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Visitor Parking", "Children's Play Area", "Jogging Track", "Garden", "Library", "Party Hall"],
    },
    {
        "title": "Residential Villa Plot Shamshabad 200 Sq Yards",
        "description": "Premium villa plot in a gated community near Shamshabad airport. HMDA approved with all approvals in place. Well-developed infrastructure with roads, drainage, electricity, and water supply. Excellent investment opportunity with airport expansion and pharma city development nearby.",
        "price": 4500000, "property_type": "plot", "listing_type": "sale",
        "bedrooms": None, "bathrooms": None, "balconies": None, "area_sqft": 1800, "carpet_area_sqft": None,
        "floor": None, "total_floors": None, "property_age": None, "facing": "East",
        "furnishing": None, "parking": None, "construction_status": None,
        "locality": "Shamshabad", "city": "Hyderabad", "state": "Telangana", "pincode": "501218",
        "latitude": 17.2410, "longitude": 78.4280, "builder_name": "Sri Sai Developers",
        "project_name": "Sri Sai Green Valley",
        "price_per_sqft": 2500,
        "amenity_names": ["24/7 Security", "Garden", "Children's Play Area"],
    },
    {
        "title": "Independent Villa Jubilee Hills 4BHK",
        "description": "Luxurious independent villa in Jubilee Hills with private garden and terrace. Premium location in one of Hyderabad's most prestigious neighborhoods. Features Italian marble, smart home automation, private pool provision, and 3-car garage. Close to GVK One Mall and KBR Park.",
        "price": 35000000, "property_type": "villa", "listing_type": "sale",
        "bedrooms": 4, "bathrooms": 5, "balconies": 2, "area_sqft": 4500, "carpet_area_sqft": 3800,
        "floor": None, "total_floors": 3, "property_age": 8, "facing": "South-East",
        "furnishing": "furnished", "parking": 3, "construction_status": "ready",
        "locality": "Jubilee Hills", "city": "Hyderabad", "state": "Telangana", "pincode": "500033",
        "latitude": 17.4318, "longitude": 78.4072, "builder_name": "Owner Built",
        "project_name": None,
        "price_per_sqft": 7778,
        "amenity_names": ["Garden", "24/7 Security", "CCTV Surveillance", "Power Backup", "Car Parking", "Water Supply", "Vastu Compliant"],
    },

    # ─── BANGALORE ────────────────────────────────────────
    {
        "title": "Prestige Falcon City 3BHK Kanakapura Road",
        "description": "Premium 3BHK in the renowned Prestige Falcon City on Kanakapura Road. 100+ acre integrated township with excellent amenities. Features high-quality construction, spacious rooms, and green surroundings. Close to NICE Junction and major tech parks.",
        "price": 12000000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 2, "balconies": 2, "area_sqft": 1580, "carpet_area_sqft": 1340,
        "floor": 6, "total_floors": 14, "property_age": 5, "facing": "East",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Kanakapura Road", "city": "Bangalore", "state": "Karnataka", "pincode": "560062",
        "latitude": 12.8770, "longitude": 77.5735, "builder_name": "Prestige Group",
        "project_name": "Prestige Falcon City", "is_featured": True,
        "price_per_sqft": 7594, "maintenance_charge": 5500,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Tennis Court", "Basketball Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Jogging Track", "Garden", "Indoor Games", "Party Hall", "Rain Water Harvesting"],
    },
    {
        "title": "Sobha Dream Acres 2BHK Panathur",
        "description": "Elegant 2BHK in Sobha Dream Acres, one of Bangalore's landmark projects. Located near ORR with quick access to Whitefield and Sarjapur Road tech hubs. The 80-acre campus features extensive landscaping, sports facilities, and a premium clubhouse.",
        "price": 8500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1100, "carpet_area_sqft": 935,
        "floor": 11, "total_floors": 20, "property_age": 3, "facing": "North",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Panathur", "city": "Bangalore", "state": "Karnataka", "pincode": "560103",
        "latitude": 12.9340, "longitude": 77.7010, "builder_name": "Sobha Limited",
        "project_name": "Sobha Dream Acres",
        "price_per_sqft": 7727, "maintenance_charge": 4000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Badminton Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Jogging Track", "Garden", "Co-working Space"],
    },
    {
        "title": "Brigade Lakefront 3BHK Whitefield Premium",
        "description": "Premium 3BHK overlooking Whitefield's Varthur Lake. World-class construction by Brigade Group with lake-facing balconies, premium fixtures, and smart home ready wiring. Located in the IT corridor with ITPL, Phoenix Marketcity, and top international schools nearby.",
        "price": 14500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 3, "balconies": 2, "area_sqft": 1750, "carpet_area_sqft": 1487,
        "floor": 14, "total_floors": 22, "property_age": 2, "facing": "South-East",
        "furnishing": "semi-furnished", "parking": 2, "construction_status": "ready",
        "locality": "Whitefield", "city": "Bangalore", "state": "Karnataka", "pincode": "560066",
        "latitude": 12.9698, "longitude": 77.7499, "builder_name": "Brigade Group",
        "project_name": "Brigade Lakefront", "is_featured": True,
        "price_per_sqft": 8285, "maintenance_charge": 7000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Tennis Court", "Spa", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Visitor Parking", "Children's Play Area", "Jogging Track", "Party Hall", "Library", "EV Charging", "Solar Panel"],
    },
    {
        "title": "Salarpuria Greenage 2BHK Hosur Road",
        "description": "Smart 2BHK in Salarpuria Greenage near Electronic City. Value-for-money with good construction quality. Close to Infosys and Wipro campuses. Well-connected by BMTC and upcoming metro line. Ideal for working professionals in the Electronic City belt.",
        "price": 6200000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1080, "carpet_area_sqft": 918,
        "floor": 4, "total_floors": 16, "property_age": 6, "facing": "West",
        "furnishing": "unfurnished", "parking": 1, "construction_status": "ready",
        "locality": "Hosur Road", "city": "Bangalore", "state": "Karnataka", "pincode": "560100",
        "latitude": 12.8459, "longitude": 77.6601, "builder_name": "Salarpuria Sattva",
        "project_name": "Salarpuria Greenage",
        "price_per_sqft": 5740, "maintenance_charge": 3200,
        "amenity_names": ["Swimming Pool", "Gym", "24/7 Security", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Rain Water Harvesting"],
    },
    {
        "title": "Godrej Splendour 3BHK Electronic City",
        "description": "Contemporary 3BHK in Godrej Splendour. Premium finishes with branded fittings, large windows for natural light, and efficient layouts. Located in the heart of Electronic City Phase 1 with excellent connectivity to Silk Board via Elevated Expressway.",
        "price": 9800000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 2, "balconies": 2, "area_sqft": 1450, "carpet_area_sqft": 1232,
        "floor": 9, "total_floors": 18, "property_age": 1, "facing": "North-East",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Electronic City", "city": "Bangalore", "state": "Karnataka", "pincode": "560100",
        "latitude": 12.8399, "longitude": 77.6770, "builder_name": "Godrej Properties",
        "project_name": "Godrej Splendour",
        "price_per_sqft": 6758, "maintenance_charge": 4500,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Badminton Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Jogging Track", "Yoga Room", "Indoor Games"],
    },
    {
        "title": "Purva Atmosphere 2BHK Thanisandra",
        "description": "Stylish 2BHK in Purva Atmosphere, Thanisandra Main Road. Quick access to Manyata Tech Park and Hebbal Flyover. Modern amenities with sky lounge, infinity pool, and landscaped rooftop garden. Growing neighborhood with good social infrastructure.",
        "price": 7800000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1180, "carpet_area_sqft": 1003,
        "floor": 16, "total_floors": 24, "property_age": 2, "facing": "South",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Thanisandra", "city": "Bangalore", "state": "Karnataka", "pincode": "560077",
        "latitude": 13.0583, "longitude": 77.6368, "builder_name": "Puravankara",
        "project_name": "Purva Atmosphere",
        "price_per_sqft": 6610, "maintenance_charge": 3800,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Jogging Track", "Garden", "Co-working Space", "EV Charging"],
    },
    {
        "title": "Mantri Serenity 4BHK Kanakapura Luxury",
        "description": "Ultra-premium 4BHK penthouse in Mantri Serenity. Double-height living room, private terrace with jacuzzi provision, Italian marble, and panoramic views. Exclusive community with limited units and personalized services.",
        "price": 28000000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 4, "bathrooms": 4, "balconies": 3, "area_sqft": 3400, "carpet_area_sqft": 2890,
        "floor": 20, "total_floors": 22, "property_age": 1, "facing": "East",
        "furnishing": "furnished", "parking": 3, "construction_status": "ready",
        "locality": "Kanakapura Road", "city": "Bangalore", "state": "Karnataka", "pincode": "560062",
        "latitude": 12.8810, "longitude": 77.5750, "builder_name": "Mantri Developers",
        "project_name": "Mantri Serenity",
        "price_per_sqft": 8235, "maintenance_charge": 15000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Tennis Court", "Spa", "Yoga Room", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Visitor Parking", "Children's Play Area", "Jogging Track", "Party Hall", "Library", "Indoor Games", "EV Charging", "Solar Panel", "Vastu Compliant"],
    },
    {
        "title": "Prestige Lakeside Habitat 2BHK Varthur",
        "description": "Compact 2BHK in Prestige Lakeside Habitat. Part of a 102-acre integrated township with its own school, convention center, and retail zone. Excellent connectivity to ORR and Whitefield. Surrounded by greenery and water bodies.",
        "price": 7500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1050, "carpet_area_sqft": 892,
        "floor": 3, "total_floors": 12, "property_age": 4, "facing": "North-West",
        "furnishing": "unfurnished", "parking": 1, "construction_status": "ready",
        "locality": "Varthur", "city": "Bangalore", "state": "Karnataka", "pincode": "560087",
        "latitude": 12.9416, "longitude": 77.7400, "builder_name": "Prestige Group",
        "project_name": "Prestige Lakeside Habitat",
        "price_per_sqft": 7142, "maintenance_charge": 3500,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "24/7 Security", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Jogging Track", "Garden", "Indoor Games", "Rain Water Harvesting"],
    },

    # ─── MUMBAI ───────────────────────────────────────────
    {
        "title": "Lodha Amara 2BHK Kolshet Road Thane",
        "description": "Modern 2BHK in Lodha Amara, Thane. Part of a massive township with its own clubhouse, retail, and entertainment zone. Well-connected via Eastern Express Highway and Ghodbunder Road. Close to Viviana Mall and Thane station. Excellent for families looking for suburban comfort with city connectivity.",
        "price": 11500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 950, "carpet_area_sqft": 695,
        "floor": 22, "total_floors": 40, "property_age": 3, "facing": "West",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Kolshet Road", "city": "Mumbai", "state": "Maharashtra", "pincode": "400607",
        "latitude": 19.2350, "longitude": 72.9780, "builder_name": "Lodha Group",
        "project_name": "Lodha Amara", "is_featured": True,
        "price_per_sqft": 12105, "maintenance_charge": 6000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Tennis Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Jogging Track", "Garden", "Indoor Games", "Party Hall", "Waste Management"],
    },
    {
        "title": "Oberoi Realty 3BHK Goregaon East",
        "description": "Premium 3BHK in Oberoi Realty complex, Goregaon East. Offers stunning views of the Aarey forest. World-class amenities including an 80,000 sq ft clubhouse, temperature-controlled pool, and concierge services. Walking distance to Oberoi Mall and Goregaon station. RERA registered.",
        "price": 25000000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 3, "balconies": 2, "area_sqft": 1600, "carpet_area_sqft": 1200,
        "floor": 28, "total_floors": 45, "property_age": 2, "facing": "North",
        "furnishing": "semi-furnished", "parking": 2, "construction_status": "ready",
        "locality": "Goregaon East", "city": "Mumbai", "state": "Maharashtra", "pincode": "400063",
        "latitude": 19.1557, "longitude": 72.8498, "builder_name": "Oberoi Realty",
        "project_name": "Oberoi Woods",
        "price_per_sqft": 15625, "maintenance_charge": 12000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Spa", "Tennis Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Visitor Parking", "Children's Play Area", "Jogging Track", "Party Hall", "Library", "Co-working Space", "EV Charging"],
    },
    {
        "title": "Hiranandani Fortune City 2BHK Panvel",
        "description": "Smart 2BHK in Hiranandani Fortune City, Panvel. New Mumbai's most exciting development with neo-Gothic architecture, wide roads, and integrated township planning. Close to upcoming Navi Mumbai International Airport. Excellent appreciation potential.",
        "price": 7500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1000, "carpet_area_sqft": 720,
        "floor": 15, "total_floors": 25, "property_age": 1, "facing": "East",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Panvel", "city": "Mumbai", "state": "Maharashtra", "pincode": "410206",
        "latitude": 18.9894, "longitude": 73.1175, "builder_name": "Hiranandani",
        "project_name": "Hiranandani Fortune City",
        "price_per_sqft": 7500, "maintenance_charge": 4000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Jogging Track", "Rain Water Harvesting"],
    },
    {
        "title": "Rustomjee Urbania 1BHK Majiwada Thane",
        "description": "Affordable 1BHK in Rustomjee Urbania, Majiwada. One of Thane's best-connected locations, minutes from Thane station and Eastern Express Highway. Compact, efficient layout with modern fittings. Ideal for first-time buyers or investors. Growing micro-market with strong rental demand.",
        "price": 6500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 1, "bathrooms": 1, "balconies": 1, "area_sqft": 580, "carpet_area_sqft": 430,
        "floor": 18, "total_floors": 35, "property_age": 4, "facing": "South",
        "furnishing": "unfurnished", "parking": 1, "construction_status": "ready",
        "locality": "Majiwada", "city": "Mumbai", "state": "Maharashtra", "pincode": "400601",
        "latitude": 19.2072, "longitude": 72.9726, "builder_name": "Rustomjee",
        "project_name": "Rustomjee Urbania",
        "price_per_sqft": 11206, "maintenance_charge": 3500,
        "amenity_names": ["Swimming Pool", "Gym", "24/7 Security", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Intercom", "Water Supply"],
    },
    {
        "title": "Raymond Realty Ten X 2BHK Pokhran Road Thane",
        "description": "Elegant 2BHK in Raymond Realty's maiden real estate venture, Ten X Habitat. Features Raymond's signature quality with premium finishes. Located on Pokhran Road 2, close to Thane's civic and social infrastructure. Walkable to schools, hospitals, and entertainment zones.",
        "price": 9800000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 880, "carpet_area_sqft": 650,
        "floor": 12, "total_floors": 30, "property_age": 2, "facing": "North-East",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Pokhran Road", "city": "Mumbai", "state": "Maharashtra", "pincode": "400610",
        "latitude": 19.2277, "longitude": 72.9755, "builder_name": "Raymond Realty",
        "project_name": "Ten X Habitat",
        "price_per_sqft": 11136, "maintenance_charge": 5000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Badminton Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Jogging Track", "Indoor Games", "Piped Gas"],
    },
    {
        "title": "Runwal Forests 3BHK Kanjurmarg West",
        "description": "Spacious 3BHK in Runwal Forests, Kanjurmarg. Surrounded by lush green forests of Sanjay Gandhi National Park vicinity. Easy access to LBS Road and Eastern Express Highway. Close to R-City Mall and upcoming metro stations. Great for nature-loving families.",
        "price": 16000000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 2, "balconies": 2, "area_sqft": 1200, "carpet_area_sqft": 900,
        "floor": 20, "total_floors": 38, "property_age": 3, "facing": "West",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Kanjurmarg", "city": "Mumbai", "state": "Maharashtra", "pincode": "400078",
        "latitude": 19.1280, "longitude": 72.9340, "builder_name": "Runwal Group",
        "project_name": "Runwal Forests",
        "price_per_sqft": 13333, "maintenance_charge": 7500,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Tennis Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Visitor Parking", "Children's Play Area", "Jogging Track", "Garden", "Party Hall", "Yoga Room", "Waste Management"],
    },

    # ─── ADDITIONAL DIVERSITY ─────────────────────────────
    {
        "title": "DLF Cyber City 2BHK Gurgaon",
        "description": "Modern 2BHK in DLF Cyber City complex, Gurgaon. Premium location in India's leading corporate hub. Close to Rapid Metro, Ambience Mall, and Fortune 500 offices. Features contemporary design, high ceilings, and smart home wiring.",
        "price": 13000000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1200, "carpet_area_sqft": 1020,
        "floor": 15, "total_floors": 28, "property_age": 4, "facing": "East",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Cyber City", "city": "Gurgaon", "state": "Haryana", "pincode": "122002",
        "latitude": 28.4945, "longitude": 77.0888, "builder_name": "DLF Limited",
        "project_name": "DLF Cyber Terraces",
        "price_per_sqft": 10833, "maintenance_charge": 6000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Jogging Track", "Co-working Space"],
    },
    {
        "title": "Gaur Yamuna City 2BHK Greater Noida",
        "description": "Affordable 2BHK in Gaur Yamuna City, Greater Noida. Part of an integrated sports city with cricket stadium and golf course. Close to Jewar International Airport (upcoming) and Yamuna Expressway. Ideal investment with significant appreciation expected.",
        "price": 3800000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1050, "carpet_area_sqft": 893,
        "floor": 8, "total_floors": 14, "property_age": 5, "facing": "North",
        "furnishing": "unfurnished", "parking": 1, "construction_status": "ready",
        "locality": "Yamuna Expressway", "city": "Greater Noida", "state": "Uttar Pradesh", "pincode": "201306",
        "latitude": 28.4670, "longitude": 77.5250, "builder_name": "Gaursons",
        "project_name": "Gaur Yamuna City",
        "price_per_sqft": 3619, "maintenance_charge": 2000,
        "amenity_names": ["Swimming Pool", "Gym", "24/7 Security", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Basketball Court"],
    },
    {
        "title": "Casagrand First City 3BHK OMR Chennai",
        "description": "Elegant 3BHK in Casagrand First City on OMR (IT Expressway), Chennai. Close to Siruseri IT Park, Wipro campus, and ELCOT SEZ. Features large rooms with cross ventilation, premium tiles, and German kitchen fittings. Growing neighborhood with excellent rental demand.",
        "price": 8500000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 2, "balconies": 2, "area_sqft": 1520, "carpet_area_sqft": 1292,
        "floor": 7, "total_floors": 15, "property_age": 2, "facing": "East",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "OMR", "city": "Chennai", "state": "Tamil Nadu", "pincode": "600119",
        "latitude": 12.8320, "longitude": 80.2210, "builder_name": "Casagrand",
        "project_name": "Casagrand First City",
        "price_per_sqft": 5592, "maintenance_charge": 4000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Badminton Court", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Jogging Track", "Rain Water Harvesting", "Piped Gas"],
    },
    {
        "title": "Godrej Eternity 2BHK Keshavnagar Pune",
        "description": "Thoughtfully designed 2BHK in Godrej Eternity, Keshavnagar, Pune. Features spacious layouts, green-certified building, and panoramic views. Close to Magarpatta City, Koregaon Park, and Pune Airport. Family-friendly environment with schools and hospitals nearby.",
        "price": 6800000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1100, "carpet_area_sqft": 770,
        "floor": 10, "total_floors": 18, "property_age": 3, "facing": "South-East",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Keshavnagar", "city": "Pune", "state": "Maharashtra", "pincode": "411036",
        "latitude": 18.5185, "longitude": 73.9290, "builder_name": "Godrej Properties",
        "project_name": "Godrej Eternity",
        "price_per_sqft": 6181, "maintenance_charge": 3500,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Jogging Track", "Garden", "Solar Panel", "Rain Water Harvesting"],
    },

    # ─── More Hyderabad for depth ─────────────────────────
    {
        "title": "Aliens Space Station 2BHK Tellapur",
        "description": "Futuristic 2BHK in Aliens Space Station, Tellapur. One of the largest townships in Hyderabad with its own commercial hub, school, and hospital. Excellent connectivity via ORR and NH-65. Close to Gachibowli and Financial District. Rapidly developing neighborhood.",
        "price": 4800000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1100, "carpet_area_sqft": 935,
        "floor": 6, "total_floors": 15, "property_age": 3, "facing": "North-East",
        "furnishing": "semi-furnished", "parking": 1, "construction_status": "ready",
        "locality": "Tellapur", "city": "Hyderabad", "state": "Telangana", "pincode": "502032",
        "latitude": 17.4530, "longitude": 78.2810, "builder_name": "Aliens Group",
        "project_name": "Aliens Space Station",
        "price_per_sqft": 4363, "maintenance_charge": 2500,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "24/7 Security", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Jogging Track"],
    },
    {
        "title": "Sumadhura Eden Garden 3BHK Bachupally",
        "description": "Spacious 3BHK in Sumadhura Eden Garden, Bachupally. Growing IT corridor between Gachibowli and Patancheru. Close to IIT Hyderabad and major pharma companies. Excellent connectivity via ORR. Features large rooms, premium flooring, and green campus with 70% open space.",
        "price": 5800000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 2, "balconies": 2, "area_sqft": 1380, "carpet_area_sqft": 1173,
        "floor": 4, "total_floors": 12, "property_age": 2, "facing": "East",
        "furnishing": "unfurnished", "parking": 1, "construction_status": "ready",
        "locality": "Bachupally", "city": "Hyderabad", "state": "Telangana", "pincode": "500090",
        "latitude": 17.5420, "longitude": 78.3670, "builder_name": "Sumadhura Group",
        "project_name": "Sumadhura Eden Garden",
        "price_per_sqft": 4202, "maintenance_charge": 3000,
        "amenity_names": ["Swimming Pool", "Gym", "24/7 Security", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Jogging Track", "Badminton Court", "Indoor Games"],
    },
    {
        "title": "PBEL City 2BHK Appa Junction",
        "description": "Value-for-money 2BHK in PBEL City, Appa Junction. Well-established township with all social infrastructure in place. Close to Forum Sujana Mall, Apollo Hospital, and Attapur Metro. Features efficient layouts, vitrified flooring, and modular kitchen.",
        "price": 4200000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 980, "carpet_area_sqft": 833,
        "floor": 8, "total_floors": 14, "property_age": 7, "facing": "West",
        "furnishing": "unfurnished", "parking": 1, "construction_status": "ready",
        "locality": "Appa Junction", "city": "Hyderabad", "state": "Telangana", "pincode": "500089",
        "latitude": 17.3940, "longitude": 78.4260, "builder_name": "PBEL",
        "project_name": "PBEL City",
        "price_per_sqft": 4285, "maintenance_charge": 2200,
        "amenity_names": ["Swimming Pool", "Gym", "24/7 Security", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Intercom"],
    },
    {
        "title": "Tata Promont 3BHK Begumpet Luxury",
        "description": "Ultra-luxury 3BHK by Tata Housing in Begumpet, one of Hyderabad's most central locations. Walking distance to Begumpet Metro, Secunderabad Station, and Tank Bund. Features imported marble, smart home automation, and concierge services. Limited edition towers with panoramic city views.",
        "price": 18000000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 3, "bathrooms": 3, "balconies": 2, "area_sqft": 2200, "carpet_area_sqft": 1870,
        "floor": 22, "total_floors": 30, "property_age": 1, "facing": "South",
        "furnishing": "furnished", "parking": 2, "construction_status": "ready",
        "locality": "Begumpet", "city": "Hyderabad", "state": "Telangana", "pincode": "500016",
        "latitude": 17.4430, "longitude": 78.4710, "builder_name": "Tata Housing",
        "project_name": "Tata Promont", "is_featured": True,
        "price_per_sqft": 8181, "maintenance_charge": 10000,
        "amenity_names": ["Swimming Pool", "Gym", "Clubhouse", "Spa", "Tennis Court", "Yoga Room", "24/7 Security", "CCTV Surveillance", "Power Backup", "Lift", "Car Parking", "Visitor Parking", "Jogging Track", "Party Hall", "Library", "EV Charging", "Solar Panel", "Vastu Compliant"],
    },
    {
        "title": "Siddha Happyville 2BHK Rajarhat Kolkata",
        "description": "Contemporary 2BHK in Siddha Happyville, Rajarhat New Town. Kolkata's upcoming IT and business district. Close to Wipro, TCS, and Cognizant offices. Features modern design, efficient layout, and vibrant community. Near Eco Park and upcoming Metro connectivity.",
        "price": 4200000, "property_type": "apartment", "listing_type": "sale",
        "bedrooms": 2, "bathrooms": 2, "balconies": 1, "area_sqft": 1050, "carpet_area_sqft": 893,
        "floor": 5, "total_floors": 14, "property_age": 3, "facing": "North",
        "furnishing": "unfurnished", "parking": 1, "construction_status": "ready",
        "locality": "Rajarhat", "city": "Kolkata", "state": "West Bengal", "pincode": "700135",
        "latitude": 22.6243, "longitude": 88.4639, "builder_name": "Siddha Group",
        "project_name": "Siddha Happyville",
        "price_per_sqft": 4000, "maintenance_charge": 2500,
        "amenity_names": ["Swimming Pool", "Gym", "24/7 Security", "Power Backup", "Lift", "Car Parking", "Children's Play Area", "Garden", "Rain Water Harvesting"],
    },
]

# Generate slugs and add metadata
for i, p in enumerate(PROPERTIES):
    p["slug"] = _slug(p["title"]) + f"-{i+1}"
    p["source"] = "seed_data"
    p["is_synthetic"] = True
    p["is_active"] = True
    p["verification_status"] = "unverified"
    if "is_featured" not in p:
        p["is_featured"] = False
